### ISSUE TITLE
Login screen authentication does not work yet

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/Bicycle-Rental-System#19]

**Comment by jtlester** [comment]
Ill take a stab at this

**Comment by evanlws12** [comment]
Nahhh bro, I got this

**Comment by jtlester** [comment]
aighttt sounds good if you need any help lemme know

**Comment by evanlws12** [comment]
What are the differences between logging in as a user, worker with admin worker without admin? Do we have to account for those differences yet?

**Comment by zbear1** [comment]
From what I understand a user does not log in.  The user would be the customer who is renting the bike.  Worker can just add a user to the database.  A worker with admin privileges can add both a user and a worker.  Hope this helps, if you need anything else let me know.

**Comment by evanlws12** [comment]
Ok yeah that clears it up. If i get it to work I'll make sure it checks for admin and only shows certain buttons




- Evan L

**Comment by evanlws12** [comment]
I'm going to ask Kyle and other groups about this. The impresario framework does not make this easy

**Comment by jtlester** [comment]
I got this to work for the worker, you can close out
