### ISSUE TITLE
Text input from user needs to be localized

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/Bicycle-Rental-System#29]

**Comment by zbear1** [comment]
I am going to try to give this one a shot.

**Comment by evanlws12** [comment]
We may not need to do anything here as long as we have combo boxes instead of text. If there are any places where we can't put one then we just need to have their input converted to a key value pair. I'm not sure where we need this yet tho




- Evan L

**Comment by zbear1** [comment]
I think we would still need to have some sort of converting.  If we just
store English to the database we will still need to convert it to French.
I will probably not spend a lot of time on it either way, I just think I
have a reasonable way to do it.  I probably won't spend a lot of time on it
so if you think I should work on something else instead I will work on
renew bike.

**Comment by evanlws12** [comment]
Yeah we might still need it, but where do we need it?




- Evan L

**Comment by zbear1** [comment]
I was thinking more of when we get the data back from the database it will
need to be converted back to French for a French user.  I suppose I will
work on renew bike for now.  We could probably work on this for the final
phase if it is a issue.

**Comment by evanlws12** [comment]
I realized description is in English and there's not much else we can do about that one... So we'll have to discuss what to do about that since when renting a bike in French it's the only thing in English, and they are sure to notice

**Comment by zbear1** [comment]
I am not sure if the description will matter.  Mitra said the colors were
the thing we absolutely needed to have show up in both french and English.
I have all of the combo boxes set up to select the french based on the
English from the database using a hash map.  So if their are any other
combo boxes we can do the same.  As far as the description goes, don't
worry about it as I don't think it matters.
