### ISSUE TITLE
Change phone number max length

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/Bicycle-Rental-System#32]
It needs to be internationalized so that people can also add country codes. Someone may just need to edit the if statements in the view files and the phone number row in the database to a longer length, but we should also research the best way to store phone numbers. It may be more complicated than you think

**Comment by jtlester** [comment]
What do you mean by best way to store phone numbers, as in the DB or in the program itself?

**Comment by evanlws12** [comment]
I think both. We don't have to but there may be a sort of standard for storing and/or validating phone numbers since they have variable lengths. If not, we can just change the length to be longer
