### ISSUE TITLE
Date added category in database and calendar in rent bicycle field

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/Bicycle-Rental-System#41]

**Comment by zbear1** [comment]
I am going to try to make a calender drop down for this.

**Comment by jtlester** [comment]
Zach, i was looking into a few things and stumbled upon a calendar popup online that i tried and it seems to work fine. Its implemented in the worker view and in the class DatePicker in model. If you want to work on making it switch to french or at least use the bundle to get the strings. We can make arrays for the months, 30days/31days/28days for each corresponding months

**Comment by zbear1** [comment]
I was just working on it.  I actually have an idea how to implement the
number of days in a month while taking leap year into account that may be
better than using a bunch of different arrays so I will see if I can
implement it with yours.

**Comment by jtlester** [comment]
Ok yeah if you can thatd be sweet, but if you arent able to implement it this way and you had a better way/version you were working you can use that as well, i just indirectly stumbled upon this while looking for something else

**Comment by jtlester** [comment]
close
