### ISSUE TITLE
Drop down menus for bicycle color etc....

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/Bicycle-Rental-System#42]
After this, we need to create key/value pairs for the options so that it works for french/english

**Comment by ddriz11** [comment]
I finished color box still working on others

**Comment by ddriz11** [comment]
I did the color and condition drop downs in bicycle view let me know if there are any more otherwise we are done.

**Comment by ddriz11** [comment]
Still need french though but that can be done friday when I get the translations
