### ISSUE TITLE
Add phone number regex

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/Bicycle-Rental-System#46]

**Comment by jlapl1** [comment]
I'll take this one.

**Comment by evanlws12** [comment]
Okay that's fine. You'll probably need to have an action listener for the text area that counts how many numbers the user entered. When they put in 3 you should enter a space after the 3 numbers and when it hits 7 and 12 you may need to use regex to put another space after the first number along with a +. The standard for country codes look like "+1 415 599 2631". So basically that's what the number should look like in the text area but when they hit submit we want to use regex to get rid of everything but the numbers
