### ISSUE TITLE
Phone number input

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/Bicycle-Rental-System#77]
Phone number should have a + before it, followed by a small text area for the country code, followed by the rest of the text area for the phone number
@jlapl1 if you can figure this out that'd be great

**Comment by evanlws12** [comment]
@jlapl1 basically all we need is a small text field before the phone number field with a + symbol before that. Nothing else needs to be changed anymore. So If you could make that change real quick that'd be great!

**Comment by jtlester** [comment]
@jlapl1 dont worry bout this i got it...evan you can close this now

**Comment by jlapl1** [comment]
But I already have it done and ready to request a pull...
