### ISSUE TITLE
Modify Bike

### ISSUE THREAD

**Issue by jtlester** [evanlws12/Bicycle-Rental-System#81]
need modify bike view

**Comment by jtlester** [comment]
Ill take this one

**Comment by zbear1** [comment]
I think I already essentially did it with renew bike.

**Comment by jtlester** [comment]
Zach if you wanna work on this one with renew bike go for it, I was going too but I had a lot of other work to do last week and due the end of this week and since you already made/did rnew bike youre familiar with it. Ill just go ahead and take update worker
