### ISSUE TITLE
Little things

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/Bicycle-Rental-System#84]
I'm putting this all in one issue because the changes are small and I just want all your opinions on these:

1. What should the prompt for error first name and last name be? "Invalid first name", "Please enter your first name", "Please check first name"? The second one sounds better but what if they put in a name that is too many characters?

2.Modify bike has the combo box "In or out?" and I think we should change the name of that since it isn't clear.

3.Renew also has "BIKE" as an instance variable and the code is a bit messy. I didn't change it because i know some people are working on that file

**Comment by jtlester** [comment]
For #2, I think we should change it to available or unavailable because the status for bikes are available or unavailable

**Comment by evanlws12** [comment]
Yeah i'll fix that now, have a few minutes

**Comment by evanlws12** [comment]
Oh wait, i think zach is working on those files, i'll wait for a merge then fix #2

**Comment by zbear1** [comment]
Yeah I will be uploading Update user today.  I am not working on renew bike right now so if someone wants to make some changes go right a ahead, I just kind of threw it together in the first place.  Any changes I will make to renew bike will be Wednesday so I will make a pull request then.
