### ISSUE TITLE
Error messages in french and other popups

### ISSUE THREAD

**Issue by zbear1** [evanlws12/Bicycle-Rental-System#90]
I went through all of the error and success messages in french and these are the one that still need doing:

invalid username or password
First name is invalid
Last name is invalid
Please Select a color

also there is no success message for in neither english or french:
adding worker
modifying worker

finally there is an issue where no error popup when no password is provided when adding a worker
I will add anymore I find here, not sure if their is some overlap with any other issues but I figure I might as well include everything I noticed.

**Comment by evanlws12** [comment]
almost done with this, i'll update shortly

**Comment by evanlws12** [comment]
Just putting this here so I don't forget, there also needs to be errors for when a bike/user/worker cannot be found when searching for them in modify 

I'm also cleaning up the code (some of these are very inconsistent since everyone worked on separate parts) so expect a ton of files changed
